consumes:
- application/json
definitions:
  GoaExampleBottle:
    description: A bottle of wine (default view)
    example:
      href: Impedit alias eos voluptatibus qui.
      id: 7.263276198983628e+18
      name: Accusantium autem rerum accusamus.
    properties:
      href:
        description: API href for making requests on the bottle
        example: Impedit alias eos voluptatibus qui.
        type: string
      id:
        description: Unique bottle ID
        example: 7.263276198983628e+18
        format: int64
        type: integer
      name:
        description: Name of wine
        example: Accusantium autem rerum accusamus.
        type: string
    required:
    - id
    - href
    - name
    title: 'Mediatype identifier: application/vnd.goa.example.bottle+json; view=default'
    type: object
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609066e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609066e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
info:
  description: A simple goa service
  title: The virtual wine cellar
  version: "1"
paths:
  /bottles/{bottleID}:
    get:
      description: Get bottle by id
      operationId: bottle#show
      parameters:
      - description: Bottle ID
        in: path
        name: bottleID
        required: true
        type: integer
      produces:
      - application/vnd.goa.example.bottle+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GoaExampleBottle'
        "404":
          description: Not Found
      summary: show bottle
      tags:
      - bottle
  /docs/swagger.json:
    get:
      operationId: docs#/docs/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      summary: Download swagger/swagger.json
  /ui/{filepath}:
    get:
      operationId: swagger-ui#/ui/*filepath
      parameters:
      - description: Relative file path
        in: path
        name: filepath
        required: true
        type: string
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
        "404":
          description: File not found
          schema:
            $ref: '#/definitions/error'
      summary: Download public/swagger-ui/
produces:
- application/json
responses:
  NotFound:
    description: Not Found
  OK:
    description: OK
    schema:
      $ref: '#/definitions/GoaExampleBottle'
swagger: "2.0"
